No-Permission: "&cYou do not have permission!"
Null-World: "&cThat world does not exist!"
Player-Offline: "&cThat player is offline!"
Player-Chat-Cleaned: "&eYour chat was cleaned by %STAFF_NAME%"
All-Chat-Cleaned: "&eEverybody's chat was cleaned by %STAFF_NAME%"
World-Chat-Cleaned: "&eThe chat in this world was cleaned by %STAFF_NAME%"